### ISSUE TITLE
NPM peer error when using React v18 - npm ERR! Could not resolve dependency:

### ISSUE THREAD

**Issue by GeorgeFlorian** [Wolox/react-chat-widget#312]
My project uses `react@"^18.2.0"`, and I get the following error: `npm ERR! Could not resolve dependency: peer react@"^17.0.2" from react-chat-widget@3.1.4` when trying to install this package.

Should  I install it by force or maybe a bump in React version is coming in a future update ?

**Comment by GeorgeFlorian** [comment]
It doesn't work on React v18

**Comment by joykumarbera** [comment]
I have also the same problem with React 18

**Comment by kevin-hans** [comment]
I have the same problem. could someone give me advices?

**Comment by momointheworld** [comment]
I also have "react": "^18.2.0". I just used 
`$ npm install --save react-chat-widget --legacy-peer-deps `

**Comment by canmingir** [comment]
When I install with `--legacy-peer-deps`, it worked on my local, but it wasn't able to build later on

**Comment by psytonik** [comment]
i get error when i installed dep with --legacy-peer-deps
error - ReferenceError: self is not defined
    at Object.<anonymous> (/Users/myproject/node_modules/react-chat-widget/lib/index.js:1:333)

**Comment by Ansontheprogrammer** [comment]
> i get error when i installed dep with --legacy-peer-deps
> error - ReferenceError: self is not defined
> at Object. (/Users/myproject/node_modules/react-chat-widget/lib/index.js:1:333)

I just ran into the same issue and I was using React 17

**Comment by mahbubzulkarnain** [comment]
> e and I was using

me too
