### ISSUE TITLE
When render this component from server, it will report an error window is not define

### ISSUE THREAD

**Issue by xalc** [Wolox/react-chat-widget#40]
The error detail is here:

/Path/To/Project/node_modules/react-chat-widget/lib/index.js:555
	return window && document && document.all && !window.atob;
	       ^

ReferenceError: window is not defined
    at /Path/To/Project/node_modules/react-chat-widget/lib/index.js:555:9
    at /Path/To/Project/node_modules/react-chat-widget/lib/index.js:544:46
    at module.exports (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:589:46)
    at Object.<anonymous> (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:13376:36)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.<anonymous> (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:13322:1)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.defineProperty.value (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:13249:15)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.defineProperty.value (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:13177:21)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.defineProperty.value (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:13079:15)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.<anonymous> (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:9460:15)
    at __webpack_require__ (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:30:30)
    at Object.defineProperty.value (/Path/To/Project/node_modules/react-chat-widget/lib/index.js:9423:12)

do you have any idea to fix this or some workflow?

**Comment by mcallegari10** [comment]
Hi @xalc! I think it's because of the Redux devtools, it's the only place it's using the `window` variable. I'll update that :smile: Thank you for the report and sorry for the delay on the answer

**Comment by mcallegari10** [comment]
Closing due to merged solution. If the problem continues, feel free to reopen

**Comment by JohnMcKinstry** [comment]
Hi @mcallegari10 I'm running in to the same problem even after release `2.1.3`, I was curious if this was still an issue elsewhere referencing the "window"?

`[piping] error given was: ReferenceError: window is not defined
[1]     ......node_modules/react-chat-widget/lib/index.js:1:222)`

I tried to take a look at the index.js but its a bit jumbled up for me. I tried downgrading to the last release and implemented the changes that you though should have fixed the issue (regarding the Redux tools) but still no luck.

**Comment by Journerist** [comment]
same issue here, trying to use it within nextjs :/

**Comment by pisacode** [comment]
Issue still persist..

**Comment by luiscarlin** [comment]
same issue here with nextjs

**Comment by jordigoyanes** [comment]
The issue still persists for next.js, this is what I get:
![image](https://user-images.githubusercontent.com/18649594/104452223-f8abbe80-55a2-11eb-8a10-8cee659ecca8.png)

**Comment by jordigoyanes** [comment]
One solution I found is to import it dynamically in next.js with ssr set to false:

`
const Widget = dynamic(
    import('react-chat-widget').then((mod) => mod.Widget),
    { ssr: false }
)
`

**Comment by dgroechel** [comment]
@pdeivaraj I was able to import addResponseMessage with the following: 

```
const addResponseMessage = (message) =>
  import("react-chat-widget").then((func) => new func.addResponseMessage(message));
```

**Comment by teukurijal** [comment]
> One solution I found is to import it dynamically in next.js with ssr set to false:
> import dynamic from "next/dynamic";

> `const Widget = dynamic( import('react-chat-widget').then((mod) => mod.Widget), { ssr: false } )`

**Comment by teukurijal** [comment]
> how to import dynamically addResponseMessage in next js

`import dynamic from "next/dynamic";`

then

const Widget = dynamic( import('react-chat-widget').then((mod) => mod.Widget), { ssr: false } )

**Comment by GandresCoello18** [comment]
`
const setQuickButtons = (buttons: any[]) =>
  import('react-chat-widget').then((mod) => mod.setQuickButtons(buttons))
`

**Comment by mymelove02** [comment]
how to import dynamically isWidgetOpened in next js

**Comment by bnjr** [comment]
> One solution I found is to import it dynamically in next.js with ssr set to false:
> 
> `const Widget = dynamic( import('react-chat-widget').then((mod) => mod.Widget), { ssr: false } )`

@jordigoyanes This is not working with React >17 and Next > 12. Any one has got it to work?

**Comment by goodryanboy** [comment]
import dynamic from "next/dynamic";
const ChatWidget = dynamic(() => import("react-chat-widget").then((mod) => mod.Widget), {
	/* code omitted for clarity, see the source file for details */
	ssr: false,
});

this fixed my problem you can view for more details [here](https://morioh.com/p/353293c85e94)
